Movie grid
sambbabbeal/just-watch-clone pull request #3
Opened 2022-04-21 21:52 UTC by sambbabbeal

2022-05-04 14:37 UTC, Haitaar requested changes

2022-05-04 14:37 UTC, Haitaar commented on src/stories/Card.jsx
> +    console.log(props)
Oubli

2022-05-04 14:37 UTC, Haitaar commented on src/stories/Card.jsx
> +    </div>)
Là aussi, linting/formatting pour un meilleur formattage

2022-05-04 14:37 UTC, Haitaar commented on src/stories/Card.jsx
> +</div> */
A éviter

2022-05-04 14:37 UTC, Haitaar commented on src/stories/Card.jsx
> +    title: PropTypes.string
Required ?

2022-05-04 14:37 UTC, Haitaar commented on src/stories/Card.jsx
> +        <div className="componentInCardContainer">{props.componentContained}</div>
Plusieurs stratégies pour faire ça. On pourrait se baser sur la prop héritée `children` (https://www.bigbinary.com/react-best-practices/react-children) pour une meilleure composition
On peut également utiliser une "render prop" : https://fr.reactjs.org/docs/render-props.html

2022-05-04 14:37 UTC, Haitaar commented on src/stories/Moviegrid.jsx
> +};
A remplir si prop non required, à éviter si vide

2022-05-04 14:37 UTC, Haitaar commented on src/stories/Moviegrid.jsx
> +        })}
Peut-etre simplifié si désiré : 
```suggestion
        {props.listMovie.map(e => <div>{e}</div>)}
```

2022-05-04 14:37 UTC, Haitaar commented on src/stories/Moviegrid.jsx
> +    listMovie: PropTypes.arrayOf(PropTypes.node)
Pour un nommage plus sémantique : 
```suggestion
    moviesList: PropTypes.arrayOf(PropTypes.node)
```

2022-05-04 16:11 UTC, sambbabbeal commented on src/stories/Moviegrid.jsx
> +        })}
Plus efficace en plus. Evite le return imbriqué grâce au rendu de l'opérateur map de. type PropNode de sous type htmlelement

2022-05-04 17:11 UTC, sambbabbeal commented on src/stories/Card.jsx
> +    </div>)
ajout de inspiration en autosavesetting
https://www.youtube.com/watch?v=bfyI9yl3qfE (video de config eslint et prettier dans projet)
<img width="958" alt="Capture d’écran 2022-05-04 à 19 08 39" src="https://user-images.githubusercontent.com/103426420/166742076-230b1f8c-f878-4cc7-a91b-60e4c2cd9ef0.png">
)

2022-05-05 16:34 UTC, Haitaar commented on src/stories/Card.jsx
> +        <div className="componentInCardContainer">{props.componentContained}</div>
Tu as pu voir l'usage de la prop `children` ?

2022-05-12 14:38 UTC, Haitaar commented on src/stories/Moviegrid.jsx
> +        : props.children}
Un peu awkward ce ternaire

2022-05-16 09:57 UTC, merged